### ISSUE TITLE
reduce data sent to iframe to essentials

### ISSUE THREAD

**Issue by russellsamora** [BostonGlobe/charts#1]

**Comment by gabrielflorit** [comment]
Already in place for `baseball-spraychart`: see https://github.com/BostonGlobe/charts/blob/master/src/transforms/baseball-spraychart.js#L3-L13

**Comment by russellsamora** [comment]
yup saw that. why the different naming convention? should we keep it consistent? (hed, subhed, transform)

**Comment by gabrielflorit** [comment]
oh, I see. `trimData` is not replacing `transform`. It's another function. Chartbuilder calls it on export.

**Comment by russellsamora** [comment]
Ah gotcha good idea
